### ISSUE TITLE
Presence Channel not working

### ISSUE THREAD

**Issue by aleedhillon** [springboardVR/Laravel-Ably-Broadcaster#1]
PHP v7.3.10
Laravel v6.6.2 
Everything else is working just presence channel are not working.

**Comment by MatthewHallCom** [comment]
@aliadhillon Is there any errors? Or are messages from presence channels just not arriving?

**Comment by MatthewHallCom** [comment]
Haven't heard back so we're closing this. If anyone has reproduction steps we'd love to dig into this!

**Comment by chris-allison-achiive** [comment]
I too can't get the presence channel working. I have two clients, they can connect to the same channel, but in each case they only see themselves.

Is the presence channel working for you?

**Comment by MatthewHallCom** [comment]
@chris-allison-achiive Ably support is now built into Laravel itself (after version 7 or 8 I believe)
